import React, { useEffect } from "react";
import './development-styles.css'

import { useAuth0 } from "@auth0/auth0-react";
import NavigationFooter from "./Components/NavigationFooter";
import { Tab, TabList, TabPanel, Tabs } from "react-tabs";
import { CopyBlock, vs2015 as theme } from "react-code-blocks";


import Collapsible from 'react-collapsible'



const DeveloperAccessMenuComponent = (props) =>
{
    const { isLoading, isAuthenticated } = useAuth0();

    const [ swaggerOpen, setSwaggerOpen ] = React.useState(true);

    useEffect(() => {
        if (!isLoading && !isAuthenticated)
        {
            window.location.href = window.location.origin
        }
    })

    return (
        <div id="development">
            <link />
            <br />
            <center>
                <h1>Accessing menus through API</h1>                
            </center>
            <br /><br />
            <div className="default-offset">
                <div>
                    <p>
                        The first major API access point is the <span className="endpoint">"/Public/GetMenu"</span> access point. This public access point can be used to retreive a user menu in its entirety, including the categories with their contained items, and items with the categories they belong to.
                        A menu-access token needs to be provided as URL parameter. This token can be aquired from a menu-owners Admin Panel on the "Edit menu" page. This token is of the Json Web Token (JWT) format and is unique per menu. They cannot be self-generated as these tokens are generated by the server and signed with private keys.
                    </p>
                    <p>
                        The endpoint returns a publicly accessible version of the menu with all sensitive information stripped. The exact content of the JSON response can be found on the Swagger portal.
                    </p>
                </div>
                <br /> <br />
                
                <div>
                    <h3 className="collapsible-trigger" onClick={() => setSwaggerOpen(!swaggerOpen)}>Swagger</h3>                    
                    <Collapsible
                        open={swaggerOpen} 
                        onOpen={() => setSwaggerOpen(true)}
                        onClose={() => setSwaggerOpen(false)}
                        triggerClassName="collapsible-trigger"
                        >
                        <center>
                            <iframe src="https://fhict-ordio.github.io/general/#/Public/get_Public_GetMenu" name="myiFrame" scrolling="yes" frameBorder="0" marginHeight="0px" marginWidth="0px" height="600px" width="100%" allowFullScreen />
                        </center>
                    </Collapsible>
                    {
                        !swaggerOpen &&
                    <span>...</span>
                    }
                </div>
                
                <br /><br />
                <div>
                    <h3>Code snippets</h3>
                    <br />
                    
                    <div>
                        <Tabs>
                            <TabList>
                                <Tab>JavaScript</Tab>
                                <Tab>C#</Tab>
                            </TabList>
                                
                            <TabPanel id="js">
                                <CopyBlock 
                                    text= {"export const GetMenu = async (token) =>\n{\n    let res = await\n        fetch(\"https://86.92.40.132:1000/Public/Menu?token=\" + token, {\n            method: \"GET\",\n            headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": '*' }\n        });\n    return ((res.status === 200) ? res.json() : res);\n}"}
                                    language={"js"}
                                    showLineNumbers={true}
                                    theme={theme}
                                    codeBlock
                                />
                            </TabPanel>
                            <TabPanel id="csharp">
                                <CopyBlock 
                                    text={"using System.Net.Http.Headers;\n\npublic static HttpResponseMessage GetMenu(string token)\n{\n    using (var client = new HttpClient())\n    {\n        client.BaseAddress = new Uri(\"https://86.92.40.132:1000\");\n        client.DefaultRequestHeaders.Accept.Clear();\n        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(\"application/json\"));\n        client.DefaultRequestHeaders.Add(\"Access-Control-Allow-Origin\", \"*\");\n\n        try {\n            return await client.GetAsync(\"/Public/Menu?token=\" + token);\n        } catch (Exception ex)\n        {\n            Console.WriteLine(ex);\n            return null;\n        }\n    }\n}"}
                                    language={"cpp"}
                                    showLineNumbers={true}
                                    theme={theme}
                                    codeBlock
                                />
                            </TabPanel>
                        </Tabs>
                    </div>
                </div>
            </div>

            <NavigationFooter prevLink={"/development/api-usage"} prevText={"API usage"} />
        </div>
    );
}

export default DeveloperAccessMenuComponent;